name: Build all images

on:
  push:
    branches:
      - 'master'
    paths:
      - 'pytorch-1.8.1/torchvision-0.9.1/cuda-10.1/ffmpeg-4.2.3/opencv-4.3.0/Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_PACKAGES_TOKEN }}
      -
        name: Build and push Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: pytorch-1.8.1/torchvision-0.9.1/cuda-10.1/ffmpeg-4.2.3/opencv-4.3.0
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:1.8.1-cu101-py37  
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:1.8.1-cu101-py37
